Research question 1
Open-Research-Dojo/start-up-your-business pull request #13
Opened 2021-12-08 14:10 UTC by Semm6

Added answer and acknowledgments.

2021-12-08 14:11 UTC, JoviSimons approved these changes

2021-12-08 15:06 UTC, DirkLemmen requested changes
line 39 isn't a good sentence

2021-12-08 23:35 UTC, Semm6 commented
Changed the sentence

2021-12-09 09:07 UTC, DirkLemmen approved these changes

2021-12-09 09:07 UTC, merged